### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by jescalan** [developit/babel-preset-preact#4]
It seems like one of the dependencies wasn't added, `babel-plugin-transform-flow-strip-types`. I can't imagine I'm the first one who has noticed this, and the package hasn't been updated for well over a month. Is there a different package that most people use instead of this one?

**Comment by keuller** [comment]
I've tried to update manually the dependencies, but I still get error.

**Comment by developit** [comment]
I'd love a PR if you have the time - most people just use `babel-plugin-transform-react-jsx`:

```js
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "h" }]
  ]
}
```

I'd love to have this preset working though, it's just not something I've been dogfooding yet.

**Comment by keuller** [comment]
@developit I made a PR #5 that corrects the issue. I've tested into my current project and works fine. Please review the PR. 
Thanks.
